### ISSUE TITLE
Motor AttributeError

### ISSUE THREAD

**Issue by moas** [aio-libs/aiohttp-admin#386]
ERROR:aiohttp.server:Error handling request
Traceback (most recent call last):
  File "/home/oscar/.pyenv/versions/ads/lib/python3.6/site-packages/aiohttp/web_protocol.py", line 390, in start
    resp = await self._request_handler(request)
  File "/home/oscar/.pyenv/versions/ads/lib/python3.6/site-packages/aiohttp/web_app.py", line 352, in _handle
    resp = await handler(request)
  File "/home/oscar/.pyenv/versions/ads/lib/python3.6/site-packages/aiohttp/web_middlewares.py", line 106, in impl
    return await handler(request)
  File "/home/oscar/.pyenv/versions/ads/lib/python3.6/site-packages/aiohttp_session/__init__.py", line 149, in factory
    response = await handler(request)
  File "/home/oscar/.pyenv/versions/ads/lib/python3.6/site-packages/aiohttp/web_middlewares.py", line 106, in impl
    return await handler(request)
  File "/home/oscar/.pyenv/versions/ads/lib/python3.6/site-packages/aiohttp_admin/backends/mongo.py", line 47, in list
    count = await self._collection.find(query).count()
AttributeError: 'AsyncIOMotorCursor' object has no attribute 'count'

**Comment by jettify** [comment]
Looks like motor changed API or something like that, we should probably pin motor version or something.
