### ISSUE TITLE
trafaret 2.0.0 breaks, consider pinning version

### ISSUE THREAD

**Issue by sad-boy-uoa** [aio-libs/aiohttp-admin#487]
```
text-ferret_1  | Postgres is up - continuing...
text-ferret_1  | INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
text-ferret_1  | INFO  [alembic.runtime.migration] Will assume transactional DDL.
text-ferret_1  | Traceback (most recent call last):
text-ferret_1  |   File "/usr/local/bin/adev", line 8, in <module>
text-ferret_1  |     sys.exit(cli())
text-ferret_1  |   File "/usr/local/lib/python3.7/site-packages/click/core.py", line 764, in __call__
text-ferret_1  |     return self.main(*args, **kwargs)
text-ferret_1  |   File "/usr/local/lib/python3.7/site-packages/click/core.py", line 717, in main
text-ferret_1  |     rv = self.invoke(ctx)
text-ferret_1  |   File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
text-ferret_1  |     return _process_result(sub_ctx.command.invoke(sub_ctx))
text-ferret_1  |   File "/usr/local/lib/python3.7/site-packages/click/core.py", line 956, in invoke
text-ferret_1  |     return ctx.invoke(self.callback, **ctx.params)
text-ferret_1  |   File "/usr/local/lib/python3.7/site-packages/click/core.py", line 555, in invoke
text-ferret_1  |     return callback(*args, **kwargs)
text-ferret_1  |   File "/usr/local/lib/python3.7/site-packages/aiohttp_devtools/cli.py", line 84, in runserver
text-ferret_1  |     run_app(*_runserver(**active_config))
text-ferret_1  |   File "/usr/local/lib/python3.7/site-packages/aiohttp_devtools/runserver/main.py", line 45, in runserver
text-ferret_1  |     config.import_app_factory()
text-ferret_1  |   File "/usr/local/lib/python3.7/site-packages/aiohttp_devtools/runserver/config.py", line 134, in import_app_factory
text-ferret_1  |     module = import_module(module_path)
text-ferret_1  |   File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
text-ferret_1  |     return _bootstrap._gcd_import(name[level:], package, level)
text-ferret_1  |   File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
text-ferret_1  |   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
text-ferret_1  |   File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
text-ferret_1  |   File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
text-ferret_1  |   File "<frozen importlib._bootstrap_external>", line 728, in exec_module
text-ferret_1  |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
text-ferret_1  |   File "/report/report/app.py", line 13, in <module>
text-ferret_1  |     from .admin import setup_admin
text-ferret_1  |   File "/report/report/admin.py", line 1, in <module>
text-ferret_1  |     import aiohttp_admin
text-ferret_1  |   File "/src/aiohttp-admin/aiohttp_admin/__init__.py", line 5, in <module>
text-ferret_1  |     from .admin import (
text-ferret_1  |   File "/src/aiohttp-admin/aiohttp_admin/admin.py", line 8, in <module>
text-ferret_1  |     from .utils import json_response, validate_payload, LoginForm
text-ferret_1  |   File "/src/aiohttp-admin/aiohttp_admin/utils.py", line 50, in <module>
text-ferret_1  |     SimpleType = t.IntRaw | t.Bool | t.String | t.FloatRaw
text-ferret_1  | AttributeError: module 'trafaret' has no attribute 'IntRaw'
```

**Comment by asvetlov** [comment]
Another option is upgrading the code to be compatible with the newest trafaret. 
@Arfey would you manage it?

**Comment by Arfey** [comment]
\+

**Comment by Arfey** [comment]
https://github.com/aio-libs/aiohttp_admin/pull/490 - Done

I think we need create a new release. And in future will be great if we hard code versions of dependences in setup file.

**Comment by asvetlov** [comment]
> I think we need create a new release.

Do you have all the required permissions?

**Comment by Arfey** [comment]
I tried to create a new release with tags but we don't have this feature in our CI, so I need PyPI key for do that.

@jettify did u do release from local machine?

**Comment by Yaser-Amiri** [comment]
Any progress?!
